services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=postgres_db
      - DATABASE_URL=postgres://nest_user:nest_password@postgres_db:5432/nest_db
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    ports:
      - '5432:5432'
